openapi: '3.0.1'
info:
  version: 1.0.0
  title: Swagger Quiz Portal
  license:
    name: MIT
  description: |
    ## Quiz Portal API

    | Syntax | Description |
    | ----------- | ----------- |
    | Header | Title |
    | Paragraph | Text |

servers:
  - url: http://quiz-portal.swagger.io/v1
paths:
  /api/users:
    get:
      summary: all users
      tags: [Users]
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  User:
                    $ref: '#/components/schemas/User'
        "404":
          description: Not Found
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 404
                message: Not Found
components:
  schemas:
    User:
      type: array
      items:
        $ref: "#/components/schemas/User"
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
        message:
          type: string